// Generated by CoffeeScript 2.5.1
var AutoRouting;

import React from 'react';

import {
  BrowserRouter as Router,
  Route
} from "react-router-dom";

AutoRouting = function({routes}) {
  return <>
        <Router>
            {routes.map(function({path, title, Component, sectionClass}) {
    return <Route exact path={path} key={path}>
                    <section className={sectionClass}>
                        <Component title={title} />
                    </section>
                </Route>;
  })}
        </Router>
    </>;
};

export default AutoRouting;
